commands:
- command:
  - '%URL%api/v1/messages'
  - POST
  - messageLevel: warning
    duration: PT1H
    tags: ['%PROJECT%']
    text: resync + reindex in progress
- command: [opengrok-mirror, -I, -U, '%URL%', '%PROJECT%']
- command: [opengrok-reindex-project, --printoutput,
    --jar, /opengrok/lib/opengrok.jar, -U, '%URL%', -P, '%PROJECT%', --,
    -r, dirbased, -G, -m, '2048', --leadingWildCards, 'on',
    --threads, '128', --historyThreads, '128', --historyFileThreads, '128',
    -c, /usr/local/bin/ctags, -U, '%URL%', -H, '%PROJECT%']
- command:
  - '%URL%api/v1/messages?tag=%PROJECT%'
  - DELETE
  - 'resync + reindex in progress'
  - 'Content-type': 'text/plain'
cleanup:
- command:
  - '%URL%api/v1/messages?tag=%PROJECT%'
  - DELETE
  - 'resync + reindex in progress'
  - 'Content-type': 'text/plain'
